In [21]:
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense,Conv2D,Flatten

In [17]:
(X_train,Y_train),(X_test,Y_test) = mnist.load_data()
Y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
plt.imshow(X_train[0])
X_train[0].shape

In [19]:
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)


In [20]:
Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)

In [26]:
model = Sequential()
model.add(Conv2D(64,activation='relu',input_shape=(28,28,1),kernel_size=3))
model.add(Conv2D(32,activation = 'relu',kernel_size=3))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [28]:
model.fit(X_train,Y_train,epochs=3,validation_data=(X_test,Y_test))

Epoch 1/3
1875/1875 [==============================] - 87s 46ms/step - loss: 0.1136 - accuracy: 0.9667 - val_loss: 0.0946 - val_accuracy: 0.9734
Epoch 2/3
1875/1875 [==============================] - 88s 47ms/step - loss: 0.0578 - accuracy: 0.9815 - val_loss: 0.0765 - val_accuracy: 0.9777
Epoch 3/3
1875/1875 [==============================] - 87s 46ms/step - loss: 0.0397 - accuracy: 0.9877 - val_loss: 0.0731 - val_accuracy: 0.9799


In [32]:
model.predict(X_test[:5])

1/1 [==============================] - 0s 33ms/step


array([[3.2104988e-10, 4.8176369e-17, 2.3836771e-08, 1.4799411e-07,
        4.0879425e-17, 2.2635159e-11, 1.1677232e-15, 9.9999988e-01,
        2.8515780e-11, 5.1183333e-09],
       [2.0675284e-09, 2.0669201e-10, 1.0000000e+00, 5.9282944e-13,
        2.2533768e-14, 1.4031053e-15, 2.2137035e-10, 2.1651032e-16,
        3.9561884e-10, 1.9087955e-16],
       [8.7586240e-09, 9.9967325e-01, 2.9912155e-07, 1.2102723e-10,
        1.5913635e-04, 1.2626541e-05, 4.5300811e-07, 5.3987929e-08,
        1.5420730e-04, 2.8083433e-10],
       [9.9999166e-01, 2.5835136e-13, 7.8277554e-07, 1.8652930e-11,
        1.6688354e-08, 3.6087396e-08, 1.5291286e-06, 6.2741534e-11,
        5.3995958e-08, 6.0227139e-06],
       [2.3245363e-10, 6.5262247e-11, 1.5384921e-10, 1.3393403e-09,
        9.9999499e-01, 1.3472502e-08, 5.7538224e-13, 6.0379513e-10,
        3.4526149e-09, 4.9529613e-06]], dtype=float32)

In [33]:
Y_test[:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)